### PR TITLE
Handle undefined components

### PR DESCRIPTION
**Pull request by cameronhunter**

### CODE REVIEW

**Comment by fusepilot** [comment]
Please merge.

I was getting `TypeError: Cannot read property 'fetchers' of undefined` and this fixed it.

#4 might be related, same error.

**Comment by markdalgleish** [comment]
Can I ask why any of your components in the array would be undefined?

**Comment by cameronhunter** [comment]
Yeah, sure – the component would be undefined in this situation:

``` javascript
<Route path="/">
  <IndexRoute component={Home} />
  <Route path="/:page" component={Page} />
</Route>
```

The outer `<Route>` would have an undefined component.

**Comment by markdalgleish** [comment]
Oh, cool, that makes perfect sense. I'll try and get a patch out for this soon.

**Comment by markdalgleish** [comment]
Haha, sorry, just realised this is a PR. The code in master has changed a bit, would you mind updating your PR?

**Comment by cameronhunter** [comment]
I've created a new pull request: #10

**Pull request closed without merging**
